import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [hunger, setHunger] = useState<number>(40);
  const [comfort, setComfort] = useState<number>(60);
  const [happy, setHappy] = useState<number>(30);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          "rounded-lg bg-black p-6  max-h-[600px] max-w-[400px] shadow-lg"
        }
      >
        <div
          style={{
            backgroundImage: "url(/background.png)",
            height: "300px",
            width: "300px",
            backgroundSize: "contain",
          }}
          className="bg-contain mx-auto relative"
        >
          <div className="bg-white opacity-80 px-3">
            <span className="w-full flex space-x-3 items-center">
              <p>Hunger</p>
              <div className="relative bg-white">
                <div
                  className={`absolute w-full rounded-full h-1 bg-red-500 border w-${hunger}% `}
                ></div>
              </div>
            </span>

            <span></span>

            <span></span>
          </div>
          <img
            src="/character.png"
            className="h-[100px] absolute mx-auto bottom-5 left-[30%]"
          />
        </div>

        <div className="space-y-4 mt-6">
          <button className="border-2 hover:bg-yellow-500 hover:border-yellow-100 rounded-md border-yellow-500 bg-yellow-100 text-xl w-full">
            Feed{" "}
          </button>
          <button className="border-2 hover:bg-yellow-500 hover:border-yellow-100  rounded-md border-yellow-500 bg-yellow-100 text-xl w-full">
            Pet{" "}
          </button>
          <button className="border-2 hover:bg-yellow-500 hover:border-yellow-100  rounded-md border-yellow-500 bg-yellow-100 text-xl w-full">
            Play{" "}
          </button>
        </div>
      </main>
    </>
  );
}
